# Generated by Django 4.0.4 on 2024-01-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('direction', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.IntegerField(default=1)),
                ('is_moving', models.BooleanField(default=False)),
                ('is_operational', models.BooleanField(default=True)),
                ('is_door_open', models.BooleanField(default=False)),
                ('requests', models.ManyToManyField(blank=True, to='elevators.request')),
            ],
        ),
    ]
